# Generated by Django 5.2.12 on 2026-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_task'),
        ('tasks', '0002_task_related_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='related_tasks', to='resources.resource', verbose_name='Ресурсы'),
        ),
    ]
