# Generated by Django 5.2.12 on 2026-03-31 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка')], max_length=10, verbose_name='Тип ресурса')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='task_resources/', verbose_name='Файл')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
