# Generated by Django 5.2.12 on 2026-04-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('tasks', '0002_task_related_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_resources', to='tasks.task'),
        ),
    ]
