# Generated by Django 5.2.12 on 2026-04-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_task'),
        ('tasks', '0003_task_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_resources', to='tasks.task'),
        ),
    ]
